"""Initial revision

Revision ID: 9e5e9582d93f
Revises: 8044bf309adb
Create Date: 2025-02-24 23:36:40.747464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5e9582d93f'
down_revision: Union[str, None] = '8044bf309adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_confirmations_user_id_fkey', 'user_confirmations', type_='foreignkey')
    op.create_foreign_key(None, 'user_confirmations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_confirmations', type_='foreignkey')
    op.create_foreign_key('user_confirmations_user_id_fkey', 'user_confirmations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
