"""Change confirmation_code

Revision ID: bb6ea7b6ef88
Revises: ac420b0c7b68
Create Date: 2025-02-25 23:26:04.967949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb6ea7b6ef88'
down_revision: Union[str, None] = 'ac420b0c7b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_confirmations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_user_confirmations_confirmation_code', table_name='user_confirmations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_confirmations_confirmation_code', 'user_confirmations', ['confirmation_code'], unique=True)
    op.alter_column('user_confirmations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
